#### 라이브러리 호출

In [514]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

import seaborn as sns

import matplotlib.font_manager as fm

from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, accuracy_score
from sklearn.preprocessing import LabelEncoder

In [515]:
from sklearn.model_selection import cross_val_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.svm import SVC
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import r2_score, mean_squared_error

In [516]:
# 라이브러리 호출
import pandas as pd
from sklearn.model_selection import train_test_split

# 경고창 제거
import warnings
warnings.filterwarnings('ignore')

In [517]:
plt.rc('font', family='Malgun Gothic') # 폰트 지정
plt.rc('axes', unicode_minus=False) # 마이너스 폰트 설정
%config InlineBackend.figure_format='retina' # 그래프 글씨 뚜렷

#### 데이터 셋 불러오기

In [518]:
train_df = pd.read_csv('../model_dataset/half_features.csv',index_col=0)
train_df.head()
test_df = pd.read_csv("../model_dataset/test_features.csv",index_col=0)
test_df.head()

시장베이시스  이론베이시스   괴리율  원위안 야간변동율  원엔 야간변동율  KOSPI 전날변동율  \
2023-10-10    1.56    2.31 -0.23      0.070     0.056         0.21   
2023-10-11    2.34    2.17  0.05      0.109     0.105        -0.26   
2023-10-12    2.26    2.18  0.02      0.093     0.105         1.98   
2023-10-13    1.60    2.17 -0.17      0.043     0.036         1.21   
2023-10-16    2.08    2.11 -0.01      0.081     0.124        -0.95   

            KOSPI 야간변동율  KS200 전날변동율  KS200 야간변동율  NAS 야간변동율  ...  원달러 야간변동율  \
2023-10-10        1.156         0.11        1.264       0.39  ...      0.086   
2023-10-11        1.413         0.05        1.520       0.58  ...      0.096   
2023-10-12        0.617         1.76        0.662       0.71  ...      0.084   
2023-10-13       -0.765         1.27       -0.833      -0.63  ...      0.033   
2023-10-16       -0.559        -0.94       -0.513      -1.23  ...      0.064   

            VIX 전날변동율  VIX 당일변동율  VIX 당일변화량  JNIV 종가변동율  JNIV 전날변동율  \
2023-10-10       1.43     -9.417       2.04       -8.44       1.214   
2023-10-11      -3.79     -3.785       1.35       -1.78      -1.964   
2023-10-12      -5.52     -5.074       1.69        3.03       1.983   
2023-10-13       3.73      3.794       2.64       -1.99       1.423   
2023-10-16      15.76     16.878       4.28        0.05       0.878   

            JNIV 전날변화량  CD 전날변동율  CD 전날변화량  VKOSPI_Label  
2023-10-10        0.76    -0.261      0.01             1  
2023-10-11        0.92     0.000      0.00             0  
2023-10-12        0.69     0.000      0.00             0  
2023-10-13        0.86     0.000      0.00             0  
2023-10-16        0.93     0.000      0.00             1  

[5 rows x 30 columns]

In [519]:
# train/test셋 분리
X_train = train_df.drop(columns='VKOSPI_Label',axis=1)
y_train = train_df[['VKOSPI_Label']]
X_val = test_df.drop(columns='VKOSPI_Label',axis=1)
y_val = test_df[['VKOSPI_Label']]

### Scaling 진행
* Standard
* Minmax 

In [520]:
# # 표준화
# features_to_standardize = ['시장베이시스', '이론베이시스', '괴리율', '원위안 야간변동율', '원엔 야간변동율', 'KOSPI 전날변동율',
#        'KOSPI 야간변동율', 'KS200 전날변동율', 'KS200 야간변동율', 'NAS 야간변동율', 'NAS 당일변동율',
#        'NAS 당일변화량', 'P/C Ratio', 'CALL_vol_change(%)', 'PUT_vol_change(%)',
#        'CALL_vol_fluc', 'PUT_vol_fluc', 'S&P 야간변동율', 'S&P 당일변동율', 'S&P 당일변화량',
#        '원달러 야간변동율', 'VIX 전날변동율', 'VIX 당일변동율', 'VIX 당일변화량', 'JNIV 종가변동율',
#        'JNIV 전날변동율', 'JNIV 전날변화량', 'CD 전날변동율', 'CD 전날변화량']
# scaler_standardize = StandardScaler()
# X_train = scaler_standardize.fit_transform(X_train[features_to_standardize])
# X_val = scaler_standardize.transform(X_val[features_to_standardize])

# X_train = pd.DataFrame(X_train, columns=features_to_standardize)
# X_val = pd.DataFrame(X_val, columns=features_to_standardize)

In [521]:
# minmax 스케일링

features_to_minmax = ['시장베이시스', '이론베이시스', '괴리율', '원위안 야간변동율', '원엔 야간변동율', 'KOSPI 전날변동율',
       'KOSPI 야간변동율', 'KS200 전날변동율', 'KS200 야간변동율', 'NAS 야간변동율', 'NAS 당일변동율',
       'NAS 당일변화량', 'P/C Ratio', 'CALL_vol_change(%)', 'PUT_vol_change(%)',
       'CALL_vol_fluc', 'PUT_vol_fluc', 'S&P 야간변동율', 'S&P 당일변동율', 'S&P 당일변화량',
       '원달러 야간변동율', 'VIX 전날변동율', 'VIX 당일변동율', 'VIX 당일변화량', 'JNIV 종가변동율',
       'JNIV 전날변동율', 'JNIV 전날변화량', 'CD 전날변동율', 'CD 전날변화량']

scaler_minmax = MinMaxScaler()
X_train = scaler_minmax.fit_transform(X_train[features_to_minmax])
X_val = scaler_minmax.transform(X_val[features_to_minmax])

X_train = pd.DataFrame(X_train, columns=features_to_minmax)
X_val = pd.DataFrame(X_val, columns=features_to_minmax)

### RF 기반 feature importance

In [522]:
# # Feature_Importances

# rfc = RandomForestClassifier(random_state=42)

# rfc.fit(X_train, y_train)

# rfc.feature_importances_

# ftr_importances = pd.Series(rfc.feature_importances_, index=X_train.columns)
# sorted_feature_importance = ftr_importances.sort_values(ascending=True)

# data = sorted_feature_importance
# importance = pd.DataFrame(data, columns=['feature importances'])
# importance

In [523]:
# plt.figure(figsize=(10, 6))
# colors = plt.cm.tab20(np.linspace(0, 1, len(importance)))

# plt.barh(importance.index, importance['feature importances'], color=colors)  # Changed to barh for horizontal bar chart
# plt.ylabel('Features')  # Changed to 'Features' for Y-axis label
# plt.xlabel('Importance')  # Changed to 'Importance' for X-axis label
# plt.title('Feature Importances')

# # Rotating x labels for better visibility if needed
# plt.xticks(rotation=45)

# # Show the plot
# plt.tight_layout()
# plt.show()

### Logit기반 피쳐 갯수 선정

In [524]:
from sklearn.linear_model import LogisticRegression
from sklearn.feature_selection import SelectFromModel
import statsmodels.api as sm
import numpy as np
lr_clf = LogisticRegression()


logit = SelectFromModel(LogisticRegression())
logit.fit(X_train, y_train)
logit_support = logit.get_support()
lr_feature = X_train.loc[:,logit_support].columns.tolist()

In [525]:
print(lr_feature)
print(len(lr_feature))

['이론베이시스', '원위안 야간변동율', 'NAS 야간변동율', 'NAS 당일변동율', 'NAS 당일변화량', 'PUT_vol_change(%)', 'S&P 야간변동율', 'S&P 당일변화량', 'VIX 전날변동율', 'VIX 당일변동율', 'VIX 당일변화량', 'JNIV 종가변동율', 'JNIV 전날변화량']
13


In [526]:
lr_feature=['이론베이시스','원위안 야간변동율', 'NAS 당일변동율', 'PUT_vol_change(%)', 
'S&P 야간변동율', 'S&P 당일변화량','VIX 당일변동율', 'VIX 당일변화량', 'JNIV 종가변동율', 'JNIV 전날변화량']

In [527]:
def vif(data):
    import pandas as pd
    from statsmodels.stats.outliers_influence import variance_inflation_factor

    # VIF 출력을 위한 데이터 프레임 형성
    vif = pd.DataFrame()

    # VIF 값과 각 Feature 이름에 대해 설정
    vif["VIF Factor"] = [variance_inflation_factor(data.values, i) for i in range(len(data.columns))]
    vif["features"] = data.columns 
                    
    # VIF 값이 높은 순으로 정렬
    vif = vif.sort_values(by="VIF Factor", ascending=False)
    vif = vif.reset_index().drop(columns='index')
    
    return vif

vif(X_train[lr_feature])

VIF Factor           features
0   28.300579          NAS 당일변동율
1   21.398001          S&P 야간변동율
2    7.678374          VIX 당일변동율
3    7.660854          VIX 당일변화량
4    7.496398          원위안 야간변동율
5    6.839102  PUT_vol_change(%)
6    6.674116          S&P 당일변화량
7    5.501163         JNIV 종가변동율
8    4.209386             이론베이시스
9    2.983946         JNIV 전날변화량

In [528]:
# lgbm = LGBMClassifier()
# lgbm.fit(X_train, y_train)
# lda_pred = lgbm.predict(X_val)
# lda_pred_proba = lgbm.predict_proba(X_val)

# get_clf_eval(y_val, lda_pred)
# get_eval_by_threshold(y_val , lda_pred_proba[:,1].reshape(-1,1), thresholds)

### 1. Wrapper : 모델링을 돌리면서 변수를 선택하는 방법

- Forward Selection(전진 선택) : 변수가 없는 상태로 시작하며 반복할 때마다 가장 중요한 변수를 추가하여 더 이상 성능의 향상이 없을 때까지 변수를 추가한다.
- Backward Elimination(후방 제거) : 모든 변수를 가지고 시작하며, 가장 덜 중요한 변수를 하나씩 제거하면서 모델의 성능을 향상시킨다. 더 이상 성능의 향상이 없을 때까지 반복한다.
- Stepwise Selection(단계별 선택): Foward Selection 과 Backward Elimination 을 결합하여 사용하는 방식으로, 모든  변수를 가지고 시작하여 가장 도움이 되지 않는 변수를 삭제하거나, 모델에서 빠져있는 변수 중에서 가장 중요한 변수를 추가하는 방법이다. 이와 같이 변수를 추가 또는 삭제를 반복한다. 반대로 아무것도 없는 모델에서 출발해 변수를 추가, 삭제를 반복할 수도 있다.

In [529]:
# # Forward Selection
# import pandas as pd
# from sklearn.linear_model import LogisticRegression

# # Forward feature selection 수행
# selected_features = []
# best_score = 0

# while len(selected_features) < train_df.shape[1]:
#     best_feature = None
#     best_model = None
#     best_score_local = 0

#     for feature in X_train.columns:
#         if feature not in selected_features:
#             features = selected_features + [feature]
#             X_train_selected = X_train[features]
#             X_val_selected = X_val[features]

#             model = LogisticRegression()
#             model.fit(X_train_selected, y_train)
#             score = model.score(X_val_selected, y_val)

#             if score > best_score_local:
#                 best_score_local = score
#                 best_feature = feature
#                 best_model = model

#     if best_score_local > best_score:
#         selected_features.append(best_feature)
#         best_score = best_score_local
#         print(f"Selected feature: {best_feature}, Accuracy: {best_score:.4f}")

#     else:
#         break

# print("\nForward selected features:")
# Forward = selected_features


In [530]:
# # Backward Elimination
# import pandas as pd
# from sklearn.model_selection import train_test_split
# from sklearn.linear_model import LogisticRegression

# # Backward feature selection 수행
# selected_features = X_train.columns.tolist()
# best_score = 0

# while len(selected_features) > 0:
#     worst_feature = None
#     best_model = None
#     best_score_local = 0

#     for feature in selected_features:
#         features = selected_features.copy()
#         features.remove(feature)

#         X_train_selected = X_train[features]
#         X_val_selected = X_val[features]

#         model = LogisticRegression()
#         model.fit(X_train_selected, y_train)
#         score = model.score(X_val_selected, y_val)

#         if score > best_score_local:
#             best_score_local = score
#             worst_feature = feature
#             best_model = model

#     if best_score_local > best_score:
#         selected_features.remove(worst_feature)
#         best_score = best_score_local
#         print(f"Removed feature: {worst_feature}, Accuracy: {best_score:.4f}")

#     else:
#         break

# print("\nFinal selected features:")
# Backward = selected_features


In [531]:
# # Stepwise Selection
# import pandas as pd
# from sklearn.model_selection import train_test_split
# from sklearn.linear_model import LogisticRegression

# # Stepwise feature selection 수행
# selected_features = []
# best_score = 0

# # Forward step
# while len(selected_features) < train_df.shape[1]:
#     best_feature = None
#     best_model = None
#     best_score_local = 0

#     for feature in X_train.columns:
#         if feature not in selected_features:
#             features = selected_features + [feature]
#             X_train_selected = X_train[features]
#             X_val_selected = X_val[features]

#             model = LogisticRegression()
#             model.fit(X_train_selected, y_train)
#             score = model.score(X_val_selected, y_val)

#             if score > best_score_local:
#                 best_score_local = score
#                 best_feature = feature
#                 best_model = model

#     if best_score_local > best_score:
#         selected_features.append(best_feature)
#         best_score = best_score_local
#         print(f"Selected feature: {best_feature}, Accuracy: {best_score:.4f}")

#     else:
#         break

# # Backward step
# while len(selected_features) > 0:
#     worst_feature = None
#     best_model = None
#     best_score_local = 0

#     for feature in selected_features:
#         features = selected_features.copy()
#         features.remove(feature)

#         X_train_selected = X_train[features]
#         X_val_selected = X_val[features]

#         model = LogisticRegression()
#         model.fit(X_train_selected, y_train)
#         score = model.score(X_val_selected, y_val)

#         if score > best_score_local:
#             best_score_local = score
#             worst_feature = feature
#             best_model = model

#     if best_score_local > best_score:
#         selected_features.remove(worst_feature)
#         best_score = best_score_local
#         print(f"Removed feature: {worst_feature}, Accuracy: {best_score:.4f}")

#     else:
#         break

# print("\nFinal selected features:")
# Stepwise = selected_features


## 3. Embedded
- Lasso, Ridge, Elastic Net 등 내장함수 사용하여 변수를 선택하는 방법

In [532]:
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import r2_score, mean_squared_error
import warnings
warnings.simplefilter('ignore')

lasso_model = LogisticRegression()
param_grid = {'penalty' : ['l1'], 
                'C' : [0.001, 0.01, 0.1, 1, 2, 5, 10],
                'solver' : ['liblinear']}

grid_search = GridSearchCV(lasso_model, param_grid=param_grid, return_train_score=True, cv=5)
grid_search.fit(X_train, y_train)

df = pd.DataFrame(grid_search.cv_results_)
df = df.sort_values(by=['rank_test_score'], ascending=True)
df[['params', 'mean_train_score', 'mean_test_score', 'rank_test_score']]
print('GridSearchCV 최적 파라미터:', grid_search.best_params_)
print('GridSearchCV 최고 정확도:{0:.4f}'.format(grid_search.best_score_))

GridSearchCV 최적 파라미터: {'C': 0.001, 'penalty': 'l1', 'solver': 'liblinear'}
GridSearchCV 최고 정확도:0.7107


In [533]:
lasso_best = LogisticRegression(C=5, penalty='l1', solver='liblinear').fit(X_train, y_train)

df_lasso = pd.DataFrame()
df_lasso['feature'] = X_train.columns
df_lasso['coef'] = lasso_best.coef_[0]
df_lasso.drop(df_lasso[df_lasso['coef']==0].index, inplace=True)
df_lasso

feature      coef
1              이론베이시스  0.718039
2                 괴리율 -0.362694
3           원위안 야간변동율 -1.803673
9           NAS 야간변동율 -1.506502
10          NAS 당일변동율  2.101627
12          P/C Ratio  0.194980
14  PUT_vol_change(%) -2.302137
15      CALL_vol_fluc  1.438149
17          S&P 야간변동율 -1.521572
19          S&P 당일변화량 -1.251749
22          VIX 당일변동율  0.850980
23          VIX 당일변화량  0.627851
24         JNIV 종가변동율  1.144600
26         JNIV 전날변화량 -0.989498
28           CD 전날변화량 -1.071104

In [534]:
# 라쏘에서 선택된 피처
lasso = df_lasso['feature'].values.tolist()
print('Lasso에서 선택된 피처 수 {0:1.0f}'.format(len(df_lasso)), '개')
lasso

Lasso에서 선택된 피처 수 15 개


['이론베이시스',
 '괴리율',
 '원위안 야간변동율',
 'NAS 야간변동율',
 'NAS 당일변동율',
 'P/C Ratio',
 'PUT_vol_change(%)',
 'CALL_vol_fluc',
 'S&P 야간변동율',
 'S&P 당일변화량',
 'VIX 당일변동율',
 'VIX 당일변화량',
 'JNIV 종가변동율',
 'JNIV 전날변화량',
 'CD 전날변화량']

#### 이전코드

In [535]:
# list_Forward = list(Forward)
# list_Backward = list(Backward)
# list_Stepwise = list(Stepwise)
# list_lasso = list(lasso)
# list_col_all = X_train.columns

In [536]:
# def func_Forward(x):
#     if x in list_Forward:
#         return 1
#     else:
#         return 0
    
# def func_Backward(x):
#     if x in list_Backward:
#         return 1
#     else:
#         return 0


# def func_Stepwise(x):
#     if x in list_Stepwise:
#         return 1
#     else:
#         return 0

    
# def func_lasso(x):
#     if x in list_lasso:
#         return 1
#     else:
#         return 0

In [537]:
# # 2번 선택된 Feature

# feature_counts = pd.DataFrame()
# feature_counts['Feature'] = list_col_all
# feature_counts['Forward'] = list_col_all.map(func_Forward)
# feature_counts['Backward'] = list_col_all.map(func_Backward)
# feature_counts['Stepwise'] = list_col_all.map(func_Stepwise)
# feature_counts['lasso'] = list_col_all.map(func_lasso)

# feature_counts["total"] = feature_counts["Forward"]+feature_counts['Backward']+feature_counts['Stepwise']+feature_counts["lasso"]
# feature_final = feature_counts[feature_counts["total"]>=2]
# list_feature_final = list(feature_final["Feature"])
# print("선택된 피쳐수 :", len(list_feature_final))
feature_final

Feature  Forward  Backward  Stepwise  lasso  total
0              시장베이시스        1         1         1      0      3
6         KOSPI 야간변동율        1         1         1      0      3
14  PUT_vol_change(%)        1         1         1      1      4

In [538]:
# np.array(feature_final[['Feature']])


In [539]:
# # 3번 선택된 Feature

# feature_counts = pd.DataFrame()
# feature_counts['Feature'] = list_col_all
# feature_counts['Forward'] = list_col_all.map(func_Forward)
# feature_counts['Backward'] = list_col_all.map(func_Backward)
# feature_counts['Stepwise'] = list_col_all.map(func_Stepwise)
# feature_counts['lasso'] = list_col_all.map(func_lasso)

# feature_counts["total"] = feature_counts["Forward"]+feature_counts['Backward']+feature_counts['Stepwise']+feature_counts["lasso"]
# feature_final = feature_counts[feature_counts["total"]>=3]
# list_feature_final = list(feature_final["Feature"])
# print("선택된 피쳐수 :", len(list_feature_final))
# feature_final

#### 모델링

In [540]:
X_train = X_train[[ '이론베이시스','원위안 야간변동율', 'NAS 당일변동율', 'PUT_vol_change(%)', 
'S&P 야간변동율', 'S&P 당일변화량','VIX 당일변동율', 'VIX 당일변화량', 'JNIV 종가변동율', 'JNIV 전날변화량']]
X_val = X_val[[ '이론베이시스','원위안 야간변동율', 'NAS 당일변동율', 'PUT_vol_change(%)', 
'S&P 야간변동율', 'S&P 당일변화량','VIX 당일변동율', 'VIX 당일변화량', 'JNIV 종가변동율', 'JNIV 전날변화량']]

In [541]:
from sklearn.model_selection import GridSearchCV
from imblearn.over_sampling import ADASYN
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
import pandas as pd
def model_basic(X_train, y_train, X_test, y_test):

    # ADASYN 오버샘플링을 적용합니다.
    ada = ADASYN(sampling_strategy='minority', random_state=42)
    X_train, y_train = ada.fit_resample(X_train, y_train)

    models = [
        LogisticRegression(),
        DecisionTreeClassifier(),
        SVC(),
        RandomForestClassifier(),
        XGBClassifier(),
        LGBMClassifier()
    ]

    rdict={'model':[],'accuracy':[],'precision':[],'recall':[],'f1_score':[]}

    
    for clf in models:
        clf = clf.fit(X_train, y_train)
        pred = clf.predict(X_test)
        results = (round(accuracy_score(y_test, pred),2),
                    round(precision_score(y_test, pred),2),
                    round(recall_score(y_test, pred),2),
                    round(f1_score(y_test, pred),2))
        rdict['model'].append(clf); 
        rdict['accuracy'].append(results[0])
        rdict['precision'].append(results[1])
        rdict['recall'].append(results[2])
        rdict['f1_score'].append(results[3])

        # print(results)

    rdf = pd.DataFrame(data=rdict)
    return rdf 

In [542]:
model_basic(X_train, y_train, X_val, y_val)

[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Number of positive: 88, number of negative: 86
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000208 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 560
[LightGBM] [Info] Number of data points in the train set: 174, number of used features: 10
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.505747 -> initscore=0.022990
[LightGBM] [Info] Start training from score 0.022990
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, bes

model  accuracy  precision  \
0                               LogisticRegression()      0.53       0.44   
1                           DecisionTreeClassifier()      0.58       0.50   
2                                              SVC()      0.47       0.38   
3  (DecisionTreeClassifier(max_features='sqrt', r...      0.68       0.75   
4  XGBClassifier(base_score=None, booster=None, c...      0.47       0.38   
5                                   LGBMClassifier()      0.63       0.57   

   recall  f1_score  
0    0.50      0.47  
1    0.38      0.43  
2    0.38      0.38  
3    0.38      0.50  
4    0.38      0.38  
5    0.50      0.53

In [543]:
from sklearn.model_selection import GridSearchCV

def model_basic_with_gridsearch(X_train, y_train, X_val, y_val):
    # 모델 및 해당 하이퍼파라미터 그리드 정의
    models_and_grids = {
        LogisticRegression(): {
            'penalty': ['l1', 'l2'],
            'C': [0.01, 0.1, 1, 10]
        },
        DecisionTreeClassifier(): {
            'max_depth': [1,3,7,10],
            'min_samples_split': [2, 5, 10],
            'min_samples_leaf': [1, 2, 4]
        },
        SVC(): {
            'C': [0.1, 1, 10],
            'kernel': ['linear', 'rbf']
        },
        RandomForestClassifier(): {
            'n_estimators': [5,10,15,20],
            'max_depth': [1,3,7,10],
            'min_samples_split': [2, 5, 10]
        },
        XGBClassifier(): {
            'n_estimators': [5,10,15,20],
            'learning_rate': [0.01, 0.1, 0.5]
        },
        LGBMClassifier(): {
            'n_estimators': [5,10,15,20],
            'learning_rate': [0.01, 0.1, 0.5]
        }
    }

    rdict = {'model': [], 'best_params': [], 'accuracy': [], 'precision': [], 'recall': [], 'f1_score': []}

    for model, grid in models_and_grids.items():
        clf = GridSearchCV(model, grid, cv=5)
        clf.fit(X_train, y_train)
        best_model = clf.best_estimator_

        pred = best_model.predict(X_val)
        results = (round(accuracy_score(y_val, pred), 2),
                   round(precision_score(y_val, pred, average='weighted'), 2),
                   round(recall_score(y_val, pred, average='weighted'), 2),
                   round(f1_score(y_val, pred, average='weighted'), 2))

        rdict['model'].append(best_model.__class__.__name__)
        rdict['best_params'].append(clf.best_params_)
        rdict['accuracy'].append(results[0])
        rdict['precision'].append(results[1])
        rdict['recall'].append(results[2])
        rdict['f1_score'].append(results[3])

    rdf = pd.DataFrame(data=rdict)
    return rdf


In [544]:
model_basic_with_gridsearch(X_train, y_train, X_val, y_val)

[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Number of positive: 28, number of negative: 68
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000034 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 314
[LightGBM] [Info] Number of data points in the train set: 96, number of used features: 10
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.291667 -> initscore=-0.887303
[LightGBM] [Info] Start training from score -0.887303
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] Found whitespace in feature_names, repla

model                                        best_params  \
0      LogisticRegression                       {'C': 0.01, 'penalty': 'l2'}   
1  DecisionTreeClassifier  {'max_depth': 3, 'min_samples_leaf': 2, 'min_s...   
2                     SVC                     {'C': 0.1, 'kernel': 'linear'}   
3  RandomForestClassifier  {'max_depth': 10, 'min_samples_split': 10, 'n_...   
4           XGBClassifier          {'learning_rate': 0.1, 'n_estimators': 5}   
5          LGBMClassifier         {'learning_rate': 0.01, 'n_estimators': 5}   

   accuracy  precision  recall  f1_score  
0      0.58       0.34    0.58      0.42  
1      0.68       0.70    0.68      0.66  
2      0.58       0.34    0.58      0.42  
3      0.74       0.82    0.74      0.70  
4      0.58       0.34    0.58      0.42  
5      0.58       0.34    0.58      0.42

In [545]:
# 성능확인 코드
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score
from sklearn.metrics import f1_score, roc_auc_score, average_precision_score


import warnings

def get_clf_eval(MDA_y_test, pred):
    confusion = confusion_matrix(MDA_y_test, pred)
    accuracy = accuracy_score(MDA_y_test, pred)
    precision = precision_score(MDA_y_test, pred)
    recall = recall_score(MDA_y_test, pred)
    roc_score = roc_auc_score(MDA_y_test, pred)
    pr_score = average_precision_score(MDA_y_test, pred)
    f1 = f1_score(MDA_y_test, pred)
    print('오차행렬')
    print(confusion)
    print('정확도: {0:.4f}, 정밀도 : {1:.4f}, 재현율:{2:.4f},F1 스코어:{3:.4f}'.format(accuracy, precision, recall, f1, roc_score))
    print('ROC 스코어: {0:.4f}, PR score : {1:.4f}'.format(roc_score, pr_score))

In [546]:
# 임계값에 따른 오차행렬및 스코어 -------->#임계값 최적 : 재현율기준(0.1)/f1기준(0.3)
from sklearn.preprocessing import Binarizer
thresholds = [0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8]

def get_eval_by_threshold(MDA_y_test, pred_proba_c1, thresholds):
    for custom_threshold in thresholds:
        binarizer = Binarizer(threshold=custom_threshold).fit(pred_proba_c1)
        custom_predict = binarizer.transform(pred_proba_c1)
        print("임곗값:", custom_threshold)
        get_clf_eval(MDA_y_test, custom_predict)
        print("---------------------------------------------------------")

In [547]:
dt = DecisionTreeClassifier()
dt.fit(X_train, y_train)
lda_pred = dt.predict(X_val)
lda_pred_proba = dt.predict_proba(X_val)

get_clf_eval(y_val, lda_pred)
get_eval_by_threshold(y_val , lda_pred_proba[:,1].reshape(-1,1), thresholds)

오차행렬
[[10  1]
 [ 4  4]]
정확도: 0.7368, 정밀도 : 0.8000, 재현율:0.5000,F1 스코어:0.6154
ROC 스코어: 0.7045, PR score : 0.6105
임곗값: 0.1
오차행렬
[[10  1]
 [ 4  4]]
정확도: 0.7368, 정밀도 : 0.8000, 재현율:0.5000,F1 스코어:0.6154
ROC 스코어: 0.7045, PR score : 0.6105
---------------------------------------------------------
임곗값: 0.2
오차행렬
[[10  1]
 [ 4  4]]
정확도: 0.7368, 정밀도 : 0.8000, 재현율:0.5000,F1 스코어:0.6154
ROC 스코어: 0.7045, PR score : 0.6105
---------------------------------------------------------
임곗값: 0.3
오차행렬
[[10  1]
 [ 4  4]]
정확도: 0.7368, 정밀도 : 0.8000, 재현율:0.5000,F1 스코어:0.6154
ROC 스코어: 0.7045, PR score : 0.6105
---------------------------------------------------------
임곗값: 0.4
오차행렬
[[10  1]
 [ 4  4]]
정확도: 0.7368, 정밀도 : 0.8000, 재현율:0.5000,F1 스코어:0.6154
ROC 스코어: 0.7045, PR score : 0.6105
---------------------------------------------------------
임곗값: 0.5


오차행렬
[[10  1]
 [ 4  4]]
정확도: 0.7368, 정밀도 : 0.8000, 재현율:0.5000,F1 스코어:0.6154
ROC 스코어: 0.7045, PR score : 0.6105
---------------------------------------------------------
임곗값: 0.6
오차행렬
[[10  1]
 [ 4  4]]
정확도: 0.7368, 정밀도 : 0.8000, 재현율:0.5000,F1 스코어:0.6154
ROC 스코어: 0.7045, PR score : 0.6105
---------------------------------------------------------
임곗값: 0.7
오차행렬
[[10  1]
 [ 4  4]]
정확도: 0.7368, 정밀도 : 0.8000, 재현율:0.5000,F1 스코어:0.6154
ROC 스코어: 0.7045, PR score : 0.6105
---------------------------------------------------------
임곗값: 0.8
오차행렬
[[10  1]
 [ 4  4]]
정확도: 0.7368, 정밀도 : 0.8000, 재현율:0.5000,F1 스코어:0.6154
ROC 스코어: 0.7045, PR score : 0.6105
---------------------------------------------------------


In [548]:
rf = RandomForestClassifier()
rf.fit(X_train, y_train)
lda_pred = rf.predict(X_val)
lda_pred_proba = rf.predict_proba(X_val)

get_clf_eval(y_val, lda_pred)
get_eval_by_threshold(y_val , lda_pred_proba[:,1].reshape(-1,1), thresholds)

오차행렬
[[11  0]
 [ 7  1]]
정확도: 0.6316, 정밀도 : 1.0000, 재현율:0.1250,F1 스코어:0.2222
ROC 스코어: 0.5625, PR score : 0.4934
임곗값: 0.1
오차행렬
[[ 1 10]
 [ 0  8]]
정확도: 0.4737, 정밀도 : 0.4444, 재현율:1.0000,F1 스코어:0.6154
ROC 스코어: 0.5455, PR score : 0.4444
---------------------------------------------------------
임곗값: 0.2
오차행렬
[[3 8]
 [0 8]]
정확도: 0.5789, 정밀도 : 0.5000, 재현율:1.0000,F1 스코어:0.6667
ROC 스코어: 0.6364, PR score : 0.5000
---------------------------------------------------------
임곗값: 0.3
오차행렬
[[8 3]
 [1 7]]
정확도: 0.7895, 정밀도 : 0.7000, 재현율:0.8750,F1 스코어:0.7778
ROC 스코어: 0.8011, PR score : 0.6651
---------------------------------------------------------
임곗값: 0.4
오차행렬
[[9 2]
 [5 3]]
정확도: 0.6316, 정밀도 : 0.6000, 재현율:0.3750,F1 스코어:0.4615
ROC 스코어: 0.5966, PR score : 0.4882
---------------------------------------------------------
임곗값: 0.5
오차행렬
[[11  0]
 [ 7  1]]
정확도: 0.6316, 정밀도 : 1.0000, 재현율:0.1250,F1 스코어:0.2222
ROC 스코어: 0.5625, PR score : 0.4934
---------------------------------------------------------
임곗값: 0.6
오차

In [549]:
ada = ADASYN(sampling_strategy='minority', random_state=42)
X_train, y_train = ada.fit_resample(X_train, y_train)


lgbm = LGBMClassifier()
lgbm.fit(X_train, y_train)
lda_pred = lgbm.predict(X_val)
lda_pred_proba = lgbm.predict_proba(X_val)

get_clf_eval(y_val, lda_pred)
get_eval_by_threshold(y_val , lda_pred_proba[:,1].reshape(-1,1), thresholds)

[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Number of positive: 88, number of negative: 86
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000085 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 560
[LightGBM] [Info] Number of data points in the train set: 174, number of used features: 10
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.505747 -> initscore=0.022990
[LightGBM] [Info] Start training from score 0.022990
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, bes

In [550]:
rf.feature_importances_

array([0.11084044, 0.09555019, 0.067153  , 0.09432301, 0.10092416,
       0.13157824, 0.09894149, 0.11343923, 0.09194081, 0.09530943])

In [551]:
X_train.columns

Index(['이론베이시스', '원위안 야간변동율', 'NAS 당일변동율', 'PUT_vol_change(%)', 'S&P 야간변동율',
       'S&P 당일변화량', 'VIX 당일변동율', 'VIX 당일변화량', 'JNIV 종가변동율', 'JNIV 전날변화량'],
      dtype='object')

In [552]:
y_val.reset_index(drop=True, inplace=True)
y_train.reset_index(drop=True, inplace=True)

In [553]:
lda_pred

array([1., 0., 1., 0., 0., 1., 0., 1., 0., 0., 0., 1., 1., 0., 0., 0., 1.,
       0., 0.])

In [554]:
a = pd.concat([X_val,y_val],axis=1)
a["pre"] = lda_pred
a

이론베이시스  원위안 야간변동율  NAS 당일변동율  PUT_vol_change(%)  S&P 야간변동율  S&P 당일변화량  \
0   0.850746   0.502762   0.847893           0.301805   0.630556   0.640695   
1   0.798507   0.718232   0.680202           0.703172   0.600000   0.465170   
2   0.802239   0.629834   0.652766           0.541234   0.575000   0.283852   
3   0.798507   0.353591   0.429763           0.403646   0.283333   0.676611   
4   0.776119   0.563536   0.254829          -0.024296   0.316667   0.744823   
5   0.735075   0.265193   0.773924           0.694022   0.750000   0.394786   
6   0.731343   0.535912   0.773924           0.479667   0.452778   0.613034   
7   0.720149   0.801105   0.382792           0.258683   0.083333   0.675742   
8   0.694030   0.651934   0.310360           0.505846   0.219444   0.813179   
9   0.671642   0.712707   0.297410           0.525578   0.105556   0.576828   
10  0.630597   0.745856   0.736172           0.195331   0.408333   0.766401   
11  0.623134   0.359116   0.679543           0.780325   0.658333   0.380159   
12  0.608209   0.353591   0.219491           0.207098   0.058333   0.540188   
13  0.578358   0.535912   0.289508           0.653367   0.127778   0.608255   
14  0.567164   1.011050   0.456980           0.257981   0.322222   0.567994   
15  0.533582   0.475138   0.654741           0.406644   0.788889   0.446488   
16  0.514925   0.414365   0.698420           0.579078   0.636111   0.416075   
17  0.507463   0.563536   0.884548           0.295648   0.747222   0.495293   
18  0.507463   0.419890   0.693152           0.463046   0.980556   0.546850   

    VIX 당일변동율  VIX 당일변화량  JNIV 종가변동율  JNIV 전날변화량  VKOSPI_Label  pre  
0    0.096850   0.574648   -0.050357    0.226852             1  1.0  
1    0.321411   0.380282    0.246435    0.300926             0  0.0  
2    0.270016   0.476056    0.460784    0.194444             0  1.0  
3    0.623604   0.743662    0.237077    0.273148             0  0.0  
4    1.145295   1.205634    0.327986    0.305556             1  0.0  
5    0.077791   0.684507    0.388146    0.425926             0  1.0  
6    0.579984   0.442254    0.523173    0.134259             0  0.0  
7    0.659091   0.639437    0.173351    0.199074             1  1.0  
8    0.809809   0.802817    0.294118    0.194444             1  0.0  
9    0.494498   0.397183    0.637701    0.305556             0  0.0  
10   0.205662   1.014085    0.470588    0.138889             0  0.0  
11   0.261324   0.447887    0.387255    0.634259             1  1.0  
12   0.636842   0.670423    0.142157    0.148148             1  1.0  
13   0.270933   0.490141    0.238859    0.375000             1  0.0  
14   0.644418   0.661972    0.704545    0.305556             0  0.0  
15   0.211922   0.453521    0.065508    0.143519             1  0.0  
16   0.126994   0.532394    0.546791    0.634259             0  1.0  
17   0.217863   0.504225    0.009804    0.046296             0  0.0  
18   0.248804   0.292958    0.105169    0.078704             0  0.0

In [555]:
b = pd.concat([X_train,y_train],axis=1)
b

이론베이시스  원위안 야간변동율  NAS 당일변동율  PUT_vol_change(%)  S&P 야간변동율  S&P 당일변화량  \
0    0.723881   0.320442   0.861282           0.449257   0.555556   0.344388   
1    0.682836   0.348066   0.787752           0.544549   0.483333   0.336713   
2    0.671642   0.314917   0.499781           0.543905   0.455556   0.115134   
3    0.656716   0.458564   0.258560           0.418294   0.341667   0.488487   
4    0.641791   0.436464   0.896400           0.416851   0.825000   0.538161   
..        ...        ...        ...                ...        ...        ...   
169  0.771247   0.617254   0.705036           0.200343   0.523380   0.241147   
170  0.918138   0.511225   0.313597           0.472457   0.081976   0.755361   
171  0.842268   0.386821   0.714451           0.356468   0.652818   0.364402   
172  0.865672   0.607713   0.575252           0.586285   0.385632   0.418053   
173  0.865672   0.557010   0.574858           0.517138   0.394499   0.412939   

     VIX 당일변동율  VIX 당일변화량  JNIV 종가변동율  JNIV 전날변화량  VKOSPI_Label  
0     0.472329   0.000000    0.351159    0.087963           1.0  
1     0.385965   0.315493    0.220143    0.092593           0.0  
2     0.476515   0.202817    0.284759    0.217593           1.0  
3     0.412679   0.487324    0.263369    0.000000           0.0  
4     0.254226   0.363380    0.291444    0.175926           0.0  
..         ...        ...         ...         ...           ...  
169   0.377325   0.359235    0.219264    0.194830           1.0  
170   0.904869   0.853679    0.389199    0.273949           1.0  
171   0.320172   0.332969    0.558209    0.335611           1.0  
172   0.246607   0.459696    0.528868    0.276162           1.0  
173   0.295721   0.436655    0.617242    0.263231           1.0  

[174 rows x 11 columns]

In [556]:
b[b["VKOSPI_Label"]==0].describe()

이론베이시스  원위안 야간변동율  NAS 당일변동율  PUT_vol_change(%)  S&P 야간변동율  \
count  86.000000  86.000000  86.000000          86.000000  86.000000   
mean    0.483556   0.467622   0.600080           0.421633   0.493637   
std     0.281673   0.174810   0.196084           0.171037   0.206104   
min     0.000000   0.176796   0.000000           0.000000   0.000000   
25%     0.242537   0.343923   0.464991           0.322700   0.356250   
50%     0.511194   0.403315   0.601405           0.416191   0.479167   
75%     0.716418   0.600829   0.709998           0.522816   0.638889   
max     1.000000   1.000000   1.000000           1.000000   1.000000   

       S&P 당일변화량  VIX 당일변동율  VIX 당일변화량  JNIV 종가변동율  JNIV 전날변화량  VKOSPI_Label  
count  86.000000  86.000000  86.000000   86.000000   86.000000          86.0  
mean    0.375033   0.411093   0.335113    0.324187    0.274009           0.0  
std     0.224809   0.174778   0.169723    0.171738    0.227205           0.0  
min     0.006807   0.000000   0.050704    0.000000    0.000000           0.0  
25%     0.187581   0.302861   0.203521    0.219474    0.101852           0.0  
50%     0.321723   0.388337   0.316901    0.294786    0.201389           0.0  
75%     0.491528   0.508423   0.431690    0.415998    0.407407           0.0  
max     1.000000   1.000000   0.828169    1.000000    1.000000           0.0

In [557]:
a[a["VKOSPI_Label"]==0].describe()

이론베이시스  원위안 야간변동율  NAS 당일변동율  PUT_vol_change(%)  S&P 야간변동율  \
count  11.000000  11.000000  11.000000          11.000000  11.000000   
mean    0.660448   0.579106   0.643387           0.467128   0.532828   
std     0.121047   0.214046   0.175465           0.167291   0.249323   
min     0.507463   0.265193   0.297410           0.195331   0.105556   
25%     0.541045   0.417127   0.554873           0.349647   0.365278   
50%     0.671642   0.563536   0.693152           0.479667   0.575000   
75%     0.766791   0.715470   0.755048           0.560156   0.691667   
max     0.802239   1.011050   0.884548           0.703172   0.980556   

       S&P 당일변화량  VIX 당일변동율  VIX 당일변화량  JNIV 종가변동율  JNIV 전날변화량  VKOSPI_Label  \
count  11.000000  11.000000  11.000000   11.000000   11.000000          11.0   
mean    0.527536   0.346459   0.557234    0.393656    0.257997           0.0   
std     0.136157   0.203655   0.205096    0.219920    0.169372           0.0   
min     0.283852   0.077791   0.292958    0.009804    0.046296           0.0   
25%     0.440623   0.211762   0.419718    0.241756    0.136574           0.0   
50%     0.546850   0.270016   0.504225    0.460784    0.273148           0.0   
75%     0.594931   0.537241   0.673239    0.534982    0.305556           0.0   
max     0.766401   0.644418   1.014085    0.704545    0.634259           0.0   

             pre  
count  11.000000  
mean    0.272727  
std     0.467099  
min     0.000000  
25%     0.000000  
50%     0.000000  
75%     0.500000  
max     1.000000

In [558]:
b[b["VKOSPI_Label"]==1].describe()

이론베이시스  원위안 야간변동율  NAS 당일변동율  PUT_vol_change(%)  S&P 야간변동율  \
count  88.000000  88.000000  88.000000          88.000000  88.000000   
mean    0.560963   0.414413   0.577828           0.398523   0.402560   
std     0.269281   0.110007   0.150341           0.140680   0.189007   
min     0.014925   0.000000   0.201493           0.056391   0.072222   
25%     0.372201   0.357407   0.491893           0.315695   0.260687   
50%     0.600145   0.386781   0.612417           0.382765   0.419528   
75%     0.810657   0.453039   0.669897           0.489313   0.539519   
max     0.985075   0.872928   0.894425           0.705376   0.786111   

       S&P 당일변화량  VIX 당일변동율  VIX 당일변화량  JNIV 종가변동율  JNIV 전날변화량  VKOSPI_Label  
count  88.000000  88.000000  88.000000   88.000000   88.000000          88.0  
mean    0.317569   0.465392   0.359549    0.354741    0.231753           1.0  
std     0.182542   0.198032   0.198164    0.143425    0.144879           0.0  
min     0.000000   0.060526   0.000000    0.000000    0.046296           1.0  
25%     0.207237   0.338780   0.193775    0.260250    0.127701           1.0  
50%     0.266202   0.426749   0.349553    0.359885    0.201695           1.0  
75%     0.430774   0.565817   0.459503    0.434548    0.283071           1.0  
max     0.878783   0.913357   1.000000    0.865865    0.768519           1.0

In [559]:
a[a["VKOSPI_Label"]==1].describe()

이론베이시스  원위안 야간변동율  NAS 당일변동율  PUT_vol_change(%)  S&P 야간변동율  \
count  8.000000   8.000000   8.000000           8.000000   8.000000   
mean   0.673041   0.530387   0.454895           0.386184   0.360417   
std    0.106885   0.148130   0.237167           0.257852   0.290137   
min    0.533582   0.353591   0.219491          -0.024296   0.058333   
25%    0.600746   0.446133   0.280838           0.245787   0.116667   
50%    0.658582   0.519337   0.346576           0.354225   0.268056   
75%    0.734142   0.585635   0.660942           0.542726   0.637500   
max    0.850746   0.801105   0.847893           0.780325   0.788889   

       S&P 당일변화량  VIX 당일변동율  VIX 당일변화량  JNIV 종가변동율  JNIV 전날변화량  VKOSPI_Label  \
count   8.000000   8.000000   8.000000    8.000000    8.000000           8.0   
mean    0.606191   0.511508   0.660563    0.197360    0.278356           1.0   
std     0.145919   0.360619   0.251397    0.144706    0.163821           0.0   
min     0.380159   0.096850   0.447887   -0.050357    0.143519           1.0   
25%     0.516763   0.248973   0.480986    0.122995    0.182870           1.0   
50%     0.624475   0.453888   0.607042    0.206105    0.212963           1.0   
75%     0.693012   0.696770   0.703521    0.302585    0.322917           1.0   
max     0.813179   1.145295   1.205634    0.387255    0.634259           1.0   

            pre  
count  8.000000  
mean   0.500000  
std    0.534522  
min    0.000000  
25%    0.000000  
50%    0.500000  
75%    1.000000  
max    1.000000

In [560]:
a[a["VKOSPI_Label"]==0].describe()

이론베이시스  원위안 야간변동율  NAS 당일변동율  PUT_vol_change(%)  S&P 야간변동율  \
count  11.000000  11.000000  11.000000          11.000000  11.000000   
mean    0.660448   0.579106   0.643387           0.467128   0.532828   
std     0.121047   0.214046   0.175465           0.167291   0.249323   
min     0.507463   0.265193   0.297410           0.195331   0.105556   
25%     0.541045   0.417127   0.554873           0.349647   0.365278   
50%     0.671642   0.563536   0.693152           0.479667   0.575000   
75%     0.766791   0.715470   0.755048           0.560156   0.691667   
max     0.802239   1.011050   0.884548           0.703172   0.980556   

       S&P 당일변화량  VIX 당일변동율  VIX 당일변화량  JNIV 종가변동율  JNIV 전날변화량  VKOSPI_Label  \
count  11.000000  11.000000  11.000000   11.000000   11.000000          11.0   
mean    0.527536   0.346459   0.557234    0.393656    0.257997           0.0   
std     0.136157   0.203655   0.205096    0.219920    0.169372           0.0   
min     0.283852   0.077791   0.292958    0.009804    0.046296           0.0   
25%     0.440623   0.211762   0.419718    0.241756    0.136574           0.0   
50%     0.546850   0.270016   0.504225    0.460784    0.273148           0.0   
75%     0.594931   0.537241   0.673239    0.534982    0.305556           0.0   
max     0.766401   0.644418   1.014085    0.704545    0.634259           0.0   

             pre  
count  11.000000  
mean    0.272727  
std     0.467099  
min     0.000000  
25%     0.000000  
50%     0.000000  
75%     0.500000  
max     1.000000

In [561]:
logit =   LogisticRegression()
logit.fit(X_train, y_train)
lda_pred = logit.predict(X_val)
lda_pred_proba = logit.predict_proba(X_val)

get_clf_eval(y_val, lda_pred)
get_eval_by_threshold(y_val , lda_pred_proba[:,1].reshape(-1,1), thresholds)

오차행렬
[[6 5]
 [4 4]]
정확도: 0.5263, 정밀도 : 0.4444, 재현율:0.5000,F1 스코어:0.4706
ROC 스코어: 0.5227, PR score : 0.4327
임곗값: 0.1
오차행렬
[[ 0 11]
 [ 0  8]]
정확도: 0.4211, 정밀도 : 0.4211, 재현율:1.0000,F1 스코어:0.5926
ROC 스코어: 0.5000, PR score : 0.4211
---------------------------------------------------------
임곗값: 0.2
오차행렬
[[ 0 11]
 [ 0  8]]
정확도: 0.4211, 정밀도 : 0.4211, 재현율:1.0000,F1 스코어:0.5926
ROC 스코어: 0.5000, PR score : 0.4211
---------------------------------------------------------
임곗값: 0.3
오차행렬
[[ 1 10]
 [ 0  8]]
정확도: 0.4737, 정밀도 : 0.4444, 재현율:1.0000,F1 스코어:0.6154
ROC 스코어: 0.5455, PR score : 0.4444
---------------------------------------------------------
임곗값: 0.4
오차행렬
[[4 7]
 [3 5]]
정확도: 0.4737, 정밀도 : 0.4167, 재현율:0.6250,F1 스코어:0.5000
ROC 스코어: 0.4943, PR score : 0.4183
---------------------------------------------------------
임곗값: 0.5
오차행렬
[[6 5]
 [4 4]]
정확도: 0.5263, 정밀도 : 0.4444, 재현율:0.5000,F1 스코어:0.4706
ROC 스코어: 0.5227, PR score : 0.4327
---------------------------------------------------------
임곗값: 0.6
오차

In [562]:
lda_pred_proba

array([[0.63213941, 0.36786059],
       [0.66937655, 0.33062345],
       [0.49817835, 0.50182165],
       [0.4134767 , 0.5865233 ],
       [0.31520322, 0.68479678],
       [0.57165753, 0.42834247],
       [0.46021837, 0.53978163],
       [0.46556685, 0.53443315],
       [0.49838335, 0.50161665],
       [0.47140128, 0.52859872],
       [0.49594587, 0.50405413],
       [0.65226174, 0.34773826],
       [0.33285093, 0.66714907],
       [0.58498903, 0.41501097],
       [0.51209992, 0.48790008],
       [0.68407654, 0.31592346],
       [0.63326775, 0.36673225],
       [0.65620423, 0.34379577],
       [0.75983056, 0.24016944]])

In [563]:
lda_pred

array([0., 0., 1., 1., 1., 0., 1., 1., 1., 1., 1., 0., 1., 0., 0., 0., 0.,
       0., 0.])